-- Batch meta tables
DROP TABLE  BATCH_STEP_EXECUTION_CONTEXT ;
DROP TABLE  BATCH_JOB_EXECUTION_CONTEXT ;
DROP TABLE  BATCH_STEP_EXECUTION ;
DROP TABLE  BATCH_JOB_EXECUTION_PARAMS ;
DROP TABLE  BATCH_JOB_EXECUTION ;
DROP TABLE  BATCH_JOB_INSTANCE ;

DROP SEQUENCE  BATCH_STEP_EXECUTION_SEQ ;
DROP SEQUENCE  BATCH_JOB_EXECUTION_SEQ ;
DROP SEQUENCE  BATCH_JOB_SEQ ;

-- LOL views
DROP MATERIALIZED VIEW VIEW_LOL2_TRENDANALYSE_1;
DROP MATERIALIZED VIEW VIEW_LOL2_TRENDANALYSE_2;
DROP SYNONYM VIEW_LOL2_TRENDANALYSE;

-- LOL Tables
DROP TABLE TBLLOL2DATA_1;
DROP TABLE TBLLOL2DATA_2;
DROP SYNONYM TBLLOL2DATA;

--LOL Sequences
DROP SEQUENCE SEQ_LOL2DATA;
